vim.keymap.set("n", "<c-7>", vim.cmd.TmuxNavigateLeft, { silent = true })
vim.keymap.set("n", "<c-8>", vim.cmd.TmuxNavigateDown, { silent = true })
vim.keymap.set("n", "<c-9>", vim.cmd.TmuxNavigateUp, { silent = true })
vim.keymap.set("n", "<c-0>", vim.cmd.TmuxNavigateRight, { silent = true })
vim.keymap.set("n", "<c-+>", vim.cmd.TmuxNavigatePrevious, { silent = true })
