<% @location = File.expand_path(@args[0]) %>
<% @name = @location.sub("#{ENV['HOME']}/", '').sub(/^code\//, '') %>
name: <%= @name %>
windows:
  - <%= @name %>:
      root: <%= @location %>
      layout: main-horizontal
      panes:
        - vim
        - clear
        - clear
