name: <%= @args[0].split('/').select{ |a| a != 'code' }.join('/') %>
root: ~/<%= @args[0] %>

windows:
  - <%= @args[0].split('/').select{ |a| a != 'code' }.join('/') %>:
      root: ~/<%= @args[0] %>
      layout: cae8,182x58,0,0[182x40,0,0,0,182x17,0,41{90x17,0,41,1,91x17,91,41,2}]
      panes:
        - vim
        -
        -
