<% @location = File.expand_path(@args[0], Dir.getwd) %>
<% @name = @location.sub("#{ENV['HOME']}/", '').sub(/^code\//, '') %>
name: <%= @name %>
windows:
  - <%= @name %>:
      root: <%= @location %>
      layout: cae8,182x58,0,0[182x40,0,0,0,182x17,0,41{90x17,0,41,1,91x17,91,41,2}]
      panes:
        - clear && vim
        - clear
        - clear
