exec 'source' . expand('~/.config/nvim/plugins.vim')
exec 'source' . expand('~/.config/nvim/appearance.vim')
exec 'source' . expand('~/.config/nvim/improvements.vim')
exec 'source' . expand('~/.config/nvim/autocommands.vim')
exec 'source' . expand('~/.config/nvim/mappings.vim')
